macro(use_catch2)
  pkg_search_module(CATCH2 REQUIRED catch2)
  if(CATCH2_FOUND)
    if(CMAKE_BUILD_TYPE STREQUAL "Debug")
      message(STATUS "CATCH2 Details")
      message("\t CATCH2_INCLUDE_DIRS: ${CATCH2_INCLUDE_DIRS}")
      message("\t CATCH2_CXX_FLAGS: ${CATCH2_CXX_FLAGS}")
      message("\t CATCH2_LDFLAGS: ${CATCH2_LDFLAGS}")
    endif()

    include_directories(${CATCH2_INCLUDE_DIRS})
    list(APPEND FLEXPIPE_DEP_CXX_FLAGS ${CATCH2_CXX_FLAGS})
    list(APPEND FLEXPIPE_DEP_INCLUDE_DIRS -I${CATCH2_INCLUDE_DIRS})
    list(APPEND FLEXPIPE_DEP_LINKER_FLAGS ${CATCH2_LDFLAGS})
  endif(CATCH2_FOUND)
endmacro()
